version: 2

models:
  - name: passenger_first_model
    description: "A starter dbt model"
    columns:
      - name: PASSENGERID
        description: "The primary key for this table"
        tests:
          - not_null
          - unique
          - dbt_utils.relationships:
              to: ref('my_first_dbt_model')   
              field: PASSENGERID
      - name: NAME
        description: " name of the passenger"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "length(NAME) > 0"  
      - name: SEX
        description: "SEX"
        tests:
          - not_null
      - name: AGE
        description: "Age of the passenger"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "AGE >= 0 AND AGE <= 120" 